# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('onion-routing', ['core','internet'])
    module.source = [
        'model/onion-routing.cc',
        #'helper/onion-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('onion-routing')
    module_test.source = [
        #'test/onion-routing-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/onion-routing-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'onion-routing'
    headers.source = [
        'model/onion-routing.h',
        #'helper/onion-routing-helper.h',
        ]

    #if bld.env.ENABLE_EXAMPLES:
        #bld.recurse('examples')

    # bld.ns3_python_bindings()

