# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def configure(conf):
    conf.env['sodium'] = conf.check_nonfatal( compiler='gcc',mandatory=False,lib='sodium',uselib_store='LS',cflags='-Wall') 


def build(bld):
    module = bld.create_ns3_module('onion-routing', ['core','internet'])
    module.source = [
        'model/onion-routing.cc',
        #'helper/onion-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('onion-routing')
    module_test.source = [
        #'test/onion-routing-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
                'examples/onion-routing-example.cc',
                'examples/onion-routing-dummy-encryption-example.cc',
               #'test/internet-apps-examples-test-suite.cc',
                ])
        module_test.use.append("LS")


    headers = bld(features='ns3header')
    headers.module = 'onion-routing'
    headers.source = [
        'model/onion-routing.h',
        #'helper/onion-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

