# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def configure(conf):
    conf.env['sodium'] = conf.check_nonfatal( compiler='gcc',mandatory=False,lib='sodium',uselib_store='LS',cflags='-Wall')



def build(bld):
    obj = bld.create_ns3_program('onion-routing-example', ['onion-routing','internet-apps','point-to-point','applications','core'])
    obj.source = 'onion-routing-example.cc'
    obj.use.append("LS")
    obj = bld.create_ns3_program('onion-routing-dummy-encryption-example', ['onion-routing','internet-apps','point-to-point','applications','core'])
    obj.source = 'onion-routing-dummy-encryption-example.cc'
    obj.use.append("LS")

