# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('onion-routing-example', ['onion-routing'])
    obj.source = 'onion-routing-example.cc'

