# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('onion_routing_wsn-example', ['onion_routing_wsn'])
    obj.source = 'onion_routing_wsn-example.cc'

